spring:
  datasource:
    #url: #jdbc:h2:tcp://localhost/~/jpatest
    url: jdbc:h2:~/jpatest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
   hibernate:
     ddl-auto: create
   properties:
     hibernate:
       show_sql: true
       format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace